### PR TITLE
RFC: how to merge CDC changes?

### PR DESCRIPTION
**Pull request by bunnie**
Is it appropriate to do a PR for these changes now?

It looks like not only do I have one small CDC fix in the USB dummy code, the eptri stuff is still outstanding.

The intention was to just do a PR for a fix that relaxes timing on betrusted during cdc mode, but actually, maybe it's time to merge all these changes given that it passes the antmicro testbench?

### CODE REVIEW

**Comment by bunnie** [comment]
And of course, the CI checks failed, because in order to test against the CDC fixes, the testbench also needs patches.

they are at

https://github.com/bunnie/usb-test-suite-cocotb-usb/tree/cdc-fixes
and
https://github.com/bunnie/usb-test-suite-testbenches/tree/cdc-work

I guess I'll leave this PR open as an RFC on how to merge these changes, if at all. Maybe we just maintain a separate branch?

**Comment by xobs** [comment]
I've submitted PRs upstream to get CDC support in the testbenches:

https://github.com/antmicro/usb-test-suite-testbenches/pull/16

https://github.com/antmicro/usb-test-suite-cocotb-usb/pull/5

If those are accepted, then you will be able to test CDC by simply adding `CDC=1` to the testbench. I'll modify `.travis.yml` to do two runs of the testbench in the future -- one where it runs with CDC enabled, and one without.

**Comment by xobs** [comment]
Note that if you switch between CDC and non-CDC, you'll need to run `make clean` -- Make has no concept of caching environment variables, so it doesn't know to rerun when that changes.

**Comment by xobs** [comment]
I went ahead and merged it.

I suspect this will cause the Fomu build to fail when it runs tomorrow, and this repository will continue to fail until upstream antmicro merges the tests. However, for now no additional changes need to be made to this branch, so I'm confident in merging it.

**Pull request merged**
